# GENERATED by libraries/onlykey/protocol/gen.py from onlykey-protocol.json - DO NOT EDIT
"""OnlyKey host<->device protocol constants (protocol_version 1).

The firmware (libraries/onlykey/okcore.h) is the authority; this module is the
single place a Python host should take message ids, setslot field ids, key type
ids, the user-input-mode enum, the challenge-code rule and response
classification from.
"""
import hashlib
from enum import Enum, IntEnum

PROTOCOL_VERSION = 1


class Message(IntEnum):
    """First byte after the 0xFF x4 header. Names are the firmware macro names;
    historical host names are aliases of the same value."""
    OKPIN = 225
    OKPINSD = 226
    OKPINSEC = 227
    OKCONNECT = 228  # sets time + opens the session; the web app's FIDO2 requests all ride on this cmd
    OKGETLABELS = 229  # buffer[5]: 'k' key labels, 'c' capabilities, else slot labels
    OKSETSLOT = 230
    OKWIPESLOT = 231
    OKSETU2FPRIV = 232  # deprecated
    OKWIPEU2FPRIV = 233  # deprecated
    OKSETU2FCERT = 234  # deprecated
    OKWIPEU2FCERT = 235  # deprecated
    OKGETPUBKEY = 236
    OKSIGN = 237
    OKWIPEPRIV = 238
    OKSETPRIV = 239
    OKDECRYPT = 240
    OKRESTORE = 241
    OKGETRESPONSE = 242
    OKPING = 243
    OKFWUPDATE = 244  # NEVER send to a developer key: converts it to production
    OKHMAC = 245
    OKWEBAUTHN = 246
    OKSETPIN = 225  # alias of OKPIN
    OKSETSDPIN = 226  # alias of OKPINSD
    OKSETPDPIN = 227  # alias of OKPINSEC
    OKSETPIN2 = 227  # alias of OKPINSEC
    OKSETTIME = 228  # alias of OKCONNECT


class MessageField(IntEnum):
    """OKSETSLOT field id (buffer[6]). kind: slot = per credential slot, setting = device-wide."""
    LABEL = 1  # slot
    USERNAME = 2  # slot
    NEXTKEY2 = 3  # slot
    DELAY2 = 4  # slot
    PASSWORD = 5  # slot
    NEXTKEY3 = 6  # slot
    DELAY3 = 7  # slot
    TFATYPE = 8  # slot
    TOTPKEY = 9  # slot
    YUBIAUTH = 10  # slot
    IDLETIMEOUT = 11  # setting
    WIPEMODE = 12  # setting
    KEYTYPESPEED = 13  # setting
    KEYLAYOUT = 14  # setting
    URL = 15  # slot
    NEXTKEY1 = 16  # slot
    DELAY1 = 17  # slot
    NEXTKEY4 = 18  # slot
    NEXTKEY5 = 19  # slot
    BACKUPKEYMODE = 20  # setting
    DERIVEDKEYMODE = 21  # setting
    STOREDKEYMODE = 22  # setting
    SECPROFILEMODE = 23  # setting
    LEDBRIGHTNESS = 24  # setting
    LOCKBUTTON = 25  # setting
    HMACMODE = 26  # setting
    SYSADMINMODE = 27  # setting
    TOUCHSENSE = 28  # setting
    YUBIANDHMAC = 29  # slot
    WEBDERIVEMODE = 30  # setting
    TFAUSERNAME = 9  # alias of TOTPKEY
    LOCKOUT = 11  # alias of IDLETIMEOUT
    TYPESPEED = 13  # alias of KEYTYPESPEED
    KBDLAYOUT = 14  # alias of KEYLAYOUT
    BACKUPMODE = 20  # alias of BACKUPKEYMODE
    SSHCHALENGEMODE = 21  # alias of DERIVEDKEYMODE
    derivedchallengeMode = 21  # alias of DERIVEDKEYMODE
    PGPCHALENGEMODE = 22  # alias of STOREDKEYMODE
    storedchallengeMode = 22  # alias of STOREDKEYMODE
    SECONDPROFILEMODE = 23  # alias of SECPROFILEMODE
    hmacchallengeMode = 26  # alias of HMACMODE
    modkeyMode = 27  # alias of SYSADMINMODE
    webderiveMode = 30  # alias of WEBDERIVEMODE


SETTING_FIELDS = frozenset([
    MessageField.IDLETIMEOUT,
    MessageField.WIPEMODE,
    MessageField.KEYTYPESPEED,
    MessageField.KEYLAYOUT,
    MessageField.BACKUPKEYMODE,
    MessageField.DERIVEDKEYMODE,
    MessageField.STOREDKEYMODE,
    MessageField.SECPROFILEMODE,
    MessageField.LEDBRIGHTNESS,
    MessageField.LOCKBUTTON,
    MessageField.HMACMODE,
    MessageField.SYSADMINMODE,
    MessageField.TOUCHSENSE,
    MessageField.WEBDERIVEMODE,
])

# When a setting may be written: 'any' (whenever unlocked), 'config_mode' (config
# mode or first init), 'first_init' (fresh device only; see the spec notes).
FIELD_WRITABLE = {
    MessageField.IDLETIMEOUT: 'any',
    MessageField.WIPEMODE: 'first_init',
    MessageField.KEYTYPESPEED: 'any',
    MessageField.KEYLAYOUT: 'any',
    MessageField.BACKUPKEYMODE: 'first_init',
    MessageField.DERIVEDKEYMODE: 'config_mode',
    MessageField.STOREDKEYMODE: 'config_mode',
    MessageField.SECPROFILEMODE: 'first_init',
    MessageField.LEDBRIGHTNESS: 'any',
    MessageField.LOCKBUTTON: 'any',
    MessageField.HMACMODE: 'config_mode',
    MessageField.SYSADMINMODE: 'config_mode',
    MessageField.TOUCHSENSE: 'config_mode',
    MessageField.WEBDERIVEMODE: 'config_mode',
}


class UserInputMode(IntEnum):
    """One enum for DERIVEDKEYMODE, STOREDKEYMODE and WEBDERIVEMODE. The key never depends on it."""
    CHALLENGE_CODE = 0
    BUTTON_PRESS = 1
    NO_PRESS = 2


USER_INPUT_MODE_FIELDS = {
    MessageField.DERIVEDKEYMODE: UserInputMode(1),  # default
    MessageField.STOREDKEYMODE: UserInputMode(1),  # default
    MessageField.WEBDERIVEMODE: UserInputMode(1),  # default
}
# Mode 2 (no press) on these fields is only honoured by firmware built with OK_ALLOW_NO_PRESS.
NO_PRESS_GATED_FIELDS = frozenset([MessageField.DERIVEDKEYMODE, MessageField.STOREDKEYMODE])


class KeyType(IntEnum):
    """Low nibble of the key_type byte on OKSETPRIV/OKGETPUBKEY for ECC/PQC slots (101-132).
    RSA slots (1-4) reuse the nibble for the key size in kilobits (1..4)."""
    ED25519 = 1
    P256R1 = 2
    P256K1 = 3
    CURVE25519 = 4
    MLKEM768 = 5
    XWING = 6
    PQC_PGP = 7
    HMACSHA1 = 9
    NACL = 1  # alias of ED25519
    NIST256P1 = 2  # alias of P256R1
    P256 = 2  # alias of P256R1
    SECP256K1 = 3  # alias of P256K1
    X25519 = 4  # alias of CURVE25519
    COMPOSITE = 7  # alias of PQC_PGP


# onlykey-cli `setkey <slot> <letter> <features> <hex>` letter -> KeyType
CLI_KEY_LETTERS = {
    'x': KeyType.ED25519,
    'n': KeyType.P256R1,
    's': KeyType.P256K1,
    'c': KeyType.CURVE25519,
    'm': KeyType.MLKEM768,
    'w': KeyType.XWING,
    'h': KeyType.HMACSHA1,
}

# What the FIDO2 web app sends as opt2 for a derive request (firmware does opt2++).
WEB_WIRE_KEY_TYPE = {
    KeyType.ED25519: 0,
    KeyType.P256R1: 1,
    KeyType.P256K1: 2,
    KeyType.CURVE25519: 3,
    KeyType.MLKEM768: 4,
    KeyType.XWING: 5,
}

KEY_TYPE_OPS = {
    KeyType.ED25519: ('sign', ),
    KeyType.P256R1: ('sign', 'decrypt', ),
    KeyType.P256K1: ('sign', 'decrypt', ),
    KeyType.CURVE25519: ('decrypt', ),
    KeyType.MLKEM768: ('decrypt', ),
    KeyType.XWING: ('decrypt', ),
    KeyType.PQC_PGP: ('sign', 'decrypt', ),
    KeyType.HMACSHA1: ('hmac', ),
}


class KeyFeature(IntEnum):
    """OR-ed into the key_type byte on OKSETPRIV."""
    DECRYPT = 32
    SIGN = 64
    BACKUP = 128


# onlykey-cli features letter -> bits
CLI_KEY_FEATURES = {
    'd': KeyFeature.DECRYPT,
    's': KeyFeature.SIGN,
    'b': KeyFeature.BACKUP | KeyFeature.DECRYPT,
}


def key_type_byte(letter, features):
    """Compose the OKSETPRIV key_type byte from the CLI letters (raises KeyError on unknown)."""
    return int(CLI_KEY_LETTERS[letter]) | int(CLI_KEY_FEATURES.get(features, 0))


class ReservedSlot(IntEnum):
    WEB_DERIVATION = 128
    HMACSHA1_2 = 129
    HMACSHA1_1 = 130
    DEFAULT_BACKUP = 131
    DERIVATION = 132
    DERIVATION_V2 = 232


# SSH/GPG agent derivation codes (slot byte). v1 = released SHA256 KDF, v2 = HKDF.
AGENT_DERIVATION = {
    'v1': {
        'pubkey_slot': 132,
        'sign': {KeyType.ED25519: 201, KeyType.P256R1: 202, KeyType.P256K1: 203},
        'decrypt': {KeyType.P256R1: 202, KeyType.P256K1: 203, KeyType.CURVE25519: 204},
    },
    'v2': {
        'pubkey_slot': 232,
        'sign': {KeyType.ED25519: 221, KeyType.P256R1: 222, KeyType.P256K1: 223},
        'decrypt': {KeyType.P256R1: 222, KeyType.P256K1: 223, KeyType.CURVE25519: 224},
    },
}


class DeriveAction(IntEnum):
    """opt1 of a FIDO2 derive request. REQ_PRESS variants never change the key."""
    DERIVE_PUBLIC_KEY = 1
    DERIVE_SHARED_SECRET = 2
    DERIVE_PUBLIC_KEY_REQ_PRESS = 3
    DERIVE_SHARED_SECRET_REQ_PRESS = 4


CHALLENGE_INDICES = (0, 15, 31)
CHALLENGE_MODULUS = 6
CHALLENGE_MODULUS_DUO = 3


def challenge_code(payload, duo=False):
    """Return the 3 button numbers the device waits for in CHALLENGE_CODE mode.

    payload is the exact request bytes the device hashes (all chunks concatenated;
    label32||ct_X for derived X-Wing decaps; label32||ct_X or the input pubkey for
    FIDO2 derives). Digit i = sha256(payload)[index_i] % modulus + 1."""
    h = hashlib.sha256(bytes(payload)).digest()
    mod = CHALLENGE_MODULUS_DUO if duo else CHALLENGE_MODULUS
    return tuple(h[i] % mod + 1 for i in CHALLENGE_INDICES)


def challenge_code_str(payload, duo=False):
    return ' '.join(str(b) for b in challenge_code(payload, duo))


ERROR_PREFIXES = ('Error', 'ERROR', 'Timeout')
SUCCESS_PREFIXES = ('Successfully', 'UNLOCKED', 'INITIALIZED', 'UNINITIALIZED', 'No PIN set')

class KnownResponse(str, Enum):
    NOT_IN_CONFIG_MODE = 'Error not in config mode'
    CONFIG_MODE_NOT_SUPPORTED = 'ERROR NOT SUPPORTED IN CONFIG MODE'
    DEVICE_LOCKED = 'Error device locked'
    WRONG_CHALLENGE = 'Error incorrect challenge was entered'
    CONFIRMATION_WINDOW_CLOSED = 'Error confirmation window closed before the button was pressed'
    PRESS_NOT_ACCEPTED = 'Error button press was not accepted'
    CONFIRMATION_TIMEOUT = 'Timeout occured while waiting for confirmation on OnlyKey'
    NO_KEY_IN_SLOT = 'Error no key set in this slot'
    INVALID_USER_INPUT_MODE = 'Error invalid user input mode'
    UNSUPPORTED_USER_INPUT_MODE = 'Error unsupported user input mode'
    LOCKED = 'INITIALIZED'
    UNINITIALIZED = 'UNINITIALIZED'
    NO_PIN = 'No PIN set, You must set a PIN first'
    SECPROFILE_FIRST_INIT_ONLY = 'Error Second Profile Mode may only be changed on first use'
    WIPE_MODE_LOCKED = 'Error Wipe Mode may not be changed'
    BACKUP_KEY_MODE_LOCKED = 'Error Backup Key Mode may not be changed'
    DERIVED_REQUEST_WRONG_SIZE = 'Error derived key request wrong size'
    DERIVED_KEY_TYPE_UNSUPPORTED = 'Error unsupported derived key type'
    PD_RETIRED = 'Error plausible deniability profile is no longer supported'


def classify_response(raw):
    """Classify a raw device report.

    Returns ('error', text) for an Error/ERROR string, ('status', text) for a
    Successfully/UNLOCKED string, otherwise ('data', bytes). The firmware reports
    status and failures as ASCII on the same channel as binary data, so hosts
    must classify, never measure."""
    b = bytes(raw)
    for p in ERROR_PREFIXES:
        if b.startswith(p.encode()):
            return 'error', b.rstrip(b'\x00').decode('ascii', 'replace')
    for p in SUCCESS_PREFIXES:
        if b.startswith(p.encode()):
            return 'status', b.rstrip(b'\x00').decode('ascii', 'replace')
    return 'data', b


def is_error(raw):
    return classify_response(raw)[0] == 'error'


# Derived keys over raw HID (slot 128): [cmd][slot][len|0xFF][keytype][label32][ct_X32?]
DERIVED_RECIPIENT_LEN = 33
DERIVED_DECAPS_LEN = 65


def derived_recipient_payload(key_type, label32):
    """Payload for the OKGETPUBKEY derived-recipient request (one chunk)."""
    label32 = bytes(label32)
    if len(label32) != 32:
        raise ValueError('label32 must be 32 bytes')
    return bytes([int(key_type) & 0x0F]) + label32


def derived_decaps_payload(key_type, label32, ct_x):
    """Payload for the OKDECRYPT derived-decaps request; also what the challenge code hashes."""
    label32, ct_x = bytes(label32), bytes(ct_x)
    if len(label32) != 32 or len(ct_x) != 32:
        raise ValueError('label32 and ct_x must be 32 bytes each')
    return bytes([int(key_type) & 0x0F]) + label32 + ct_x


CAPABILITIES_MAGIC = 202
CAPABILITIES_SELECTOR = b'c'  # OKGETLABELS buffer[5]

class CapabilityFlag(IntEnum):
    NO_PRESS_ALLOWED = 1
    DEBUG_BUILD = 2
    DUO = 4
    PQC = 8
    HKDF_V2_DERIVATION = 16


def parse_capabilities(report):
    """Parse the 64-byte capabilities report. Returns None if it is not one
    (older firmware answers OKGETLABELS 'c' with slot labels instead)."""
    b = bytes(report)
    if len(b) < 64 or b[0] != CAPABILITIES_MAGIC:
        return None
    out = {}
    out['protocol_version'] = b[1]
    out['fw_major'] = b[2]
    out['fw_minor'] = b[3]
    out['fw_patch'] = b[4]
    mask = int.from_bytes(b[5:7], 'little')
    out['key_types'] = [kt for kt in KeyType if mask & (1 << int(kt))]
    out['flags'] = [fl for fl in CapabilityFlag if b[7] & int(fl)]
    out['version'] = b[8:64].split(b'\x00', 1)[0].decode('ascii', 'replace')
    out['user_input_modes'] = {
        f.name: [m for m in UserInputMode
                 if m != UserInputMode.NO_PRESS or f not in NO_PRESS_GATED_FIELDS
                 or CapabilityFlag.NO_PRESS_ALLOWED in out['flags']]
        for f in USER_INPUT_MODE_FIELDS
    }
    return out

